Gerenciador/urls.py
from django.urls import path
from django.conf.urls import  url, include
from . import views
from Gerenciador.views import *

urlpatterns = [
    path('', views.index, name='index'),
   # path('CadastroProcesso', views.FrmCadastro, name='FrmCadastro'),
   # path('ListaProcesso', views.ListaProcesso, name='ListaProcesso'),
    url(r'^ListaProcesso$',ListaProcessoView.as_view(), name='ListaProcesso'),
    url(r'^ListaProcesso/CadastroProcesso$',CadastroProcessoView.as_view(), name='CadastroProcesso'),
    url(r'^ListaProcesso/StatusProcesso/(?P<pk>\d+)/$',StatusProcessoView.as_view(), name='StatusProcesso'),
    url(r'^ListaProcesso/Detalhe/(?P<pk>\d+)/$',DetalhesProcessoView.as_view(), name='DetalheProcesso'),

]

MeuSite/urls.py
from django.contrib import admin
from django.urls import include, path
"""
urlpatterns = [
    # Inclui as URLs do app ‘polls’
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
"""
urlpatterns = [
    path('Gerenciador/', include('Gerenciador.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views
app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
   ]

Gerenciador/models.py
from django.db import models
from datetime import datetime


# Create your models here.

class autor (models.Model):

    nome_autor = models.CharField(max_length=200)
    codigo = models.IntegerField()


    def __str__(self):
        return self.codigo
    
    def __str__(self):
        #return self.nome_autor
        return self.nome_autor
    
    def __str__(self):
        #return self.nome_autor
        return '%s - %s' % (self.nome_autor, self.codigo)

class cadastro (models.Model):

    class Meta:
        ordering = ['data_inclusao']

    fk_autor=models.ForeignKey(autor, on_delete=models.CASCADE)
    reu = models.CharField(max_length=200)
    documento = models.CharField(max_length=14)
    rua = models.CharField(max_length=200)
    numero = models.IntegerField(null=True)
    bairro = models.CharField(max_length=200)
    cidade = models.CharField(max_length=200)
    complemento = models.CharField(max_length=200, null=True,blank=True)
    cep = models.CharField(max_length=8)
    numero_processo = models.IntegerField()
    segredo = models.IntegerField(default=0 ,verbose_name='Segredo ?')
    advogado= models.IntegerField(default=0 ,verbose_name='Tem advogado ?')
    data_inclusao = models.DateTimeField(auto_now=True, verbose_name ='Incluido em')
    fk_conta =  models.IntegerField(default=0)
    
    def __str__(self):
        return self.reu
class statusgeral (models.Model):

    STATUS_ACOMPANHAMENTO = (
        (1,"I - Inicial"),
        (2,"II - Liminar"),
        (3,"III - Mandado Expedido"),
        (4,"IV - Mandado Devolvido"),
        (5,"VI - Novo Mandado"),
        (6,"VII - Baixado"),
    )

    fk_cadastro = models.ForeignKey(cadastro, on_delete=models.CASCADE)
    data_alteracao = models.DateTimeField(auto_now=True)
    status_acompanhamento = models.IntegerField(choices=STATUS_ACOMPANHAMENTO, default=1) 
    notas = models.CharField(max_length=250, null=True, blank=True)

    class Meta:
        ordering = ['data_alteracao']

Gerenciador/forms.py
# -*- coding: utf-8 -*-
from django import forms
from Gerenciador.models import *
class Frm_Cadastro_Processo(forms.ModelForm):
    
    segredo = forms.RadioSelect()
    advogado = forms.RadioSelect()
    complemento = forms.CharField(required = False)
    class Meta:
        model = cadastro
    # Campos que estarão no form
        fields = '__all__'
        exclude = ['data_inclusao','fk_conta']

class Frm_Status_Processo(forms.ModelForm):
     
    notas = forms.CharField(required = False, widget=forms.Textarea)
    
    class Meta:
        model = statusgeral
    # Campos que estarão no form
        fields = '__all__'
        exclude = ['data_alteracao','fk_cadastro']

Gerenciador/views.py
##http://pythonclub.com.br/class-based-views-django.html
##http://mindbending.org/pt/customizando-a-autenticacao-de-usuarios-no-django-19
import datetime
from .forms import *
from .models import *
from django.urls import reverse, reverse_lazy, resolve
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.db.models import Q
from django.views.generic import CreateView, ListView, DetailView
# Create your views here.

#@login_required
# ---------------------------- CADASTRO DE PROCESSOS 
class  CadastroProcessoView(CreateView):
    model = cadastro
    form_class = Frm_Cadastro_Processo
    template_name = 'Gerenciador/Frm_Cad_Processo.html'
    #success_url = reverse_lazy('Lista_Processo')

    def get_success_url(self, **kwargs):
        return reverse('StatusProcesso', kwargs={'pk': self.object.pk})
# ---------------------------- CADASTRO DE PROCESSOS STATUS DO PROCESSO
class  StatusProcessoView(CreateView):
    model = statusgeral
    form_class = Frm_Status_Processo
    template_name = 'Gerenciador/Frm_Status_Processo.html'
    success_url = reverse_lazy('ListaProcesso')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cadastro_pk = self.kwargs['pk']
        cadastro_list = cadastro.objects.get(pk=cadastro_pk)
        context.update({
            'cadastro_list': cadastro_list
        })
        return context

    def form_valid(self, form):
        form.instance.fk_cadastro_id = self.kwargs.get('pk') #self.kwargs['pk']
        return super().form_valid(form)
# ---------------------------- DETALHES DE PROCESSOS
class DetalhesProcessoView(DetailView):
    model = statusgeral
    template_name = 'Gerenciador/Detalhe_Processo.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cadastro_pk = self.kwargs['pk']
        cadastro_list = cadastro.objects.get(pk=cadastro_pk)
        statusgeral_list = statusgeral.objects.all().filter(fk_cadastro_id=cadastro_pk)
        context.update({
            'cadastro_list': cadastro_list,
            'statusgeral_list': statusgeral_list
        })
        return context

# ---------------------------- LISTA DE PROCESSOS
class ListaProcessoView(ListView):
    model = cadastro
    template_name ='Gerenciador/Lista_Processo.html'
    paginate_by = 15 
 

    def get_queryset(self, **kwargs):
        #Objeto Q ORM
        filtro_Basico = Q()
        filtro_Avancado = Q()

        # Filtros Basicos 
        f_Autor = self.request.GET.get('Autor')
        f_NumeroProcesso = self.request.GET.get('NumeroProcesso')
        f_DataInclusao = self.request.GET.get('DataInclusao')
        # Filtros Avançados
        f_Bairro = self.request.GET.get('Bairro','')
        f_Cidade = self.request.GET.get('Cidade','')
        f_Segredo = self.request.GET.get('Segredo','')
        f_Advogado = self.request.GET.get('Advogado','')


        if f_Autor is not None and f_Autor != 'Selecione Autor':
            filtro_Basico.add(Q(fk_autor=f_Autor), Q.AND)
        if f_NumeroProcesso:
            filtro_Basico.add(Q(numero_processo=f_NumeroProcesso), Q.AND)
        if f_DataInclusao:
            f_DataInclusao = datetime.strptime(f_DataInclusao, '%Y-%m-%d').date()
            filtro_Basico.add(Q(data_inclusao__date=f_DataInclusao), Q.AND)
        if filtro_Basico:
            return cadastro.objects.filter(filtro_Basico)

        if f_Bairro:
            filtro_Avancado.add(Q(bairro__icontains=f_Bairro), Q.AND)
        if f_Cidade:
            filtro_Avancado.add(Q(cidade__icontains=f_Cidade), Q.AND)
        if f_Segredo:
            filtro_Avancado.add(Q(segredo=f_Segredo), Q.AND)
        if f_Advogado:
            filtro_Avancado.add(Q(advogado=f_Advogado), Q.AND)
        if filtro_Avancado:
            return cadastro.objects.filter(filtro_Avancado)
        else:
            return cadastro.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(ListaProcessoView, self).get_context_data(**kwargs)
        context['Autor']  = autor.objects.select_related('fk_autor').values()
        return context 




def index(request):
    context = {'teste' : None}
    return render(request, 'Gerenciador/base.html', context)


def FrmCadastro(request):
    errors = []
    print(request.method)
    if request.method == 'POST':
        form = Cad_Form(request.POST)
        dados = form.data
        #print('Form é valido caralho ?',form.is_valid())
        if form.is_valid():
            form.save(commit=False)
            if ValidaDados.verificaProcesso(numero_processo = dados['numero_processo']) is False:
                errors.append("O processo já foi cadastrado")
                return render(request, 'Gerenciador/Frm_Cad_Processo.html', {'form': form,'errors':errors})
            #Salva o Form
            form.save()
            #Redireciona para pag
            return redirect(index)
    else:
       return render(request, 'Gerenciador/Frm_Cad_Processo.html', {'form': Cad_Form()})

Gerenciador/templates/Gerenciador/Detalhe_Processo.html
{% extends 'Gerenciador/base.html' %}
{% load static %} 
{% load widget_tweaks%}

{% block content %}

<form>
    <nav class="navbar navbar-light color-nav static-top">
        <div class="container justify-content-center">
            <a class="navbar-brand justify-content-center">Dados do Processo</a>
			<button type="button" class="btn btn-primary btn-sm justify-content-right">Editar Dados</button>
        </div>
    </nav>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputautor">Autor do Processo</label>
            <select name="fk_autor" class="form-control" required id="id_fk_autor" disabled>
                <option value="{{cadastro_list.fk_autor}}" selected>{{cadastro_list.fk_autor}}</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="inputnumero_processo">Número do Processo</label>
            <input type="number" name="numero_processo" class="form-control" required id="id_numero_processo" value="{{cadastro_list.numero_processo}}" disabled>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-7">
            <label for="inputnomereu">Nome do Réu</label>
            <input type="text" name="reu" maxlength="200" class="form-control" required id="id_reu" value="{{cadastro_list.reu}}" disabled>
        </div>
        <div class="form-group col-md-5">
            <label for="inputdocumento">Cpf/Cnpj</label>
            <input type="text" name="documento" maxlength="14" class="form-control" required id="id_documento" value="{{cadastro_list.documento}}" disabled>
        </div>
    </div>
    <div class="form-row">
        <label class="">Possui advogado ?</label>
        <div class="form-group col-md-4">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" name="advogado" value="0" class="custom-control-input" value="1" id="possuiadv1" {% if cadastro_list.advogado   ==  "1" %} checked="checked" {% endif %} disabled>
                <label class="custom-control-label" for="possuiadv1">Sim</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" name="advogado" value="0" class="custom-control-input" {% if cadastro_list.advogado !=  "1" %} checked="checked" {% endif %} value="0" id="possuiadv2" disabled>
                <label class="custom-control-label" for="possuiadv2">Não</label>
            </div>
        </div>
        <label class="">É segredo ?</label>
        <div class="form-group col-md-4">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" name="segredo" value="0" class="custom-control-input" {% if cadastro_list.segredo   ==  "1" %} checked="checked" {% endif %} value="1" id="segredo1" disabled>
                <label class="custom-control-label" for="segredo1">Sim</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" name="segredo" value="0" class="custom-control-input" {% if cadastro_list.segredo !=    "1" %} checked="checked" {% endif %} value="0" id="segredo2" disabled>
                <label class="custom-control-label" for="segredo2" checked>Não</label>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-light color-nav static-top">
        <div class="container justify-content-center">
            <a class="navbar-brand justify-content-center">Dados da Inicial</a>
        </div>
    </nav>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputrua">Rua</label>
            <input type="text" name="rua" maxlength="200" class="form-control" id="id_rua" value="{{cadastro_list.rua}}" disabled>
        </div>
        <div class="form-group col-md-1">
            <label for="inputnumero">Número</label>
            <input type="number" name="numero" class="form-control" id="id_numero" value="{{cadastro_list.numero}}" disabled>
        </div>
        <div class="form-group col-md-5">
            <label for="inputcomplemento">Complemento</label>
            <input type="text" name="complemento" class="form-control" id="inputcomplemento" value="  {% if cadastro_list.complemento is None %}
                                                                                                      {% else %}
                                                                                                      {{cadastro_list.complemento}}
                                                                                                      {% endif %}" disabled>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-5">
            <label for="inputbairro">Bairro</label>
            <input type="text" name="bairro" maxlength="200" class="form-control" id="id_bairro" value="{{cadastro_list.bairro}}" disabled>
        </div>
        <div class="form-group col-md-4">
            <label for="inputcidade">Cidade</label>
            <input type="text" name="cidade" maxlength="200" class="form-control" id="id_cidade" value="{{cadastro_list.cidade}}" disabled>
        </div>
        <div class="form-group col-md-3">
            <label for="inputcep">CEP</label>
            <input type="text" name="cep" maxlength="8" class="form-control" id="id_cep" value="{{cadastro_list.cep}}" disabled>
        </div>

    </div>
</form>
    <nav class="navbar navbar-light color-nav static-top">
        <div class="container justify-content-center">
            <a class="navbar-brand justify-content-center">Histórico de Status</a>
			<button type="button" class="btn btn-primary btn-sm justify-content-right">Adicionar Status</button>
        </div>
    </nav>
<!------------------------------------- TABELA DE RESULTADOS --------------------------------------->
<div class="table-responsive-sm">
    <table id="minhaTabela" class="table table-striped table-sm ">
        <thead class="thead-light">
            <tr align="center">
                <th scope="col">Data de Alteração</th>
                <th scope="col">Núm. Processo</th>
                <th scope="col">Status</th>
                <th scope="col">Observação</th>
            </tr>
        </thead>
        <tbody>
            {%for e in statusgeral_list%}
            <tr align="center">
                <td>{{e.data_alteracao | date:"d/m/Y h:s:i"}}</td>
                <td>{{e.fk_cadastro.numero_processo}}</td>
				<td>{{e.get_status_acompanhamento_display}}</td>
				<!-- Button trigger modal -->
				<td>{{e.notas.value}}{%if e.notas is not None or e.notas.value != "" %}<img data-toggle="modal" data-target="#mod_{{e.id}}" class="img img-small"  src="{% static 'Gerenciador/img/buscar.png' %}"/>{% endif %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{%for mod in statusgeral_list%}
<!-- Modal -->
<div class="modal fade" id="mod_{{mod.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Observação</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{mod.notas}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}


{% endblock %}

Gerenciador/templates/Gerenciador/Frm_Cad_Processo.html
{% extends 'Gerenciador/base.html' %}

{% load widget_tweaks%}

{% block content %}

{%if errors%}

{% render_field errors %}

{% endif %}

<form method="POST">
    <!-- Não se esqueça dessa tag -->
    {% csrf_token %}
    <nav class="navbar navbar-light color-nav static-top">
        <div class="container justify-content-center">
            <a class="navbar-brand justify-content-center">Dados do Processo</a>
        </div>
    </nav>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputautor">Autor do Processo</label>
            {% render_field form.fk_autor class+="form-control"%}
        </div>
        <div class="form-group col-md-6">
            <label for="inputnumero_processo">Número do Processo</label>
            {% render_field form.numero_processo class+="form-control"%}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-7">
            <label for="inputnomereu">Nome do Réu</label>
            {% render_field form.reu class+="form-control"%}
        </div>
        <div class="form-group col-md-5">
            <label for="inputdocumento">Cpf/Cnpj</label>
            {% render_field form.documento class+="form-control"%}
        </div>
    </div>
    <div class="form-row">
        <label class="">Possui advogado ?</label>
        <div class="form-group col-md-4">
            <div class="custom-control custom-radio custom-control-inline">
                {% render_field form.advogado class+="custom-control-input" id="possuiadv1" type="radio" value="1"%}
                <label class="custom-control-label" for="possuiadv1">Sim</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                {% render_field form.advogado class+="custom-control-input" id="possuiadv2" type="radio" value="0" checked="checked"%}
                <label class="custom-control-label" for="possuiadv2" checked>Não</label>
            </div>
        </div>
        <label class="">É segredo ?</label>
        <div class="form-group col-md-4">
            <div class="custom-control custom-radio custom-control-inline">
                {% render_field form.segredo class+="custom-control-input" id="segredo1" type="radio" value="1"%}
                <label class="custom-control-label" for="segredo1">Sim</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                {% render_field form.segredo class+="custom-control-input" id="segredo2" type="radio" value="0" checked="checked"%}
                <label class="custom-control-label" for="segredo2" checked>Não</label>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-light color-nav static-top">
        <div class="container justify-content-center">
            <a class="navbar-brand justify-content-center">Dados da Inicial</a>
        </div>
    </nav>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputrua">Rua</label>
            {% render_field form.rua class+="form-control"%}
        </div>
        <div class="form-group col-md-1">
            <label for="inputnumero">Número</label>
            {% render_field form.numero class="form-control"%}
        </div>
        <div class="form-group col-md-5">
            <label for="inputcomplemento">Complemento</label>
            {% render_field form.complemento class+="form-control" id="inputcomplemento" %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-5">
            <label for="inputbairro">Bairro</label>
            {% render_field form.bairro class+="form-control"%}
        </div>
        <div class="form-group col-md-4">
            <label for="inputcidade">Cidade</label>
            {% render_field form.cidade class+="form-control" %}
        </div>
        <div class="form-group col-md-3">
            <label for="inputcep">CEP</label>
            {% render_field form.cep class+="form-control"%}
        </div>

    </div>
    <a href={% url 'ListaProcesso' %} class="btn btn-danger btn-sm">Cancelar</a>
    <button type="submit" class="btn btn-success btn-sm">Finalizar Cadastro</button>
</form>


{% endblock %}

Gerenciador/templates/Gerenciador/Frm_Status_Processo.html
{% extends 'Gerenciador/base.html' %}

{% load widget_tweaks%}

{% block content %}
<form method="POST">
    <!-- Não se esqueça dessa tag -->
    {% csrf_token %}
    <nav class="navbar navbar-light color-nav static-top">
        <div class="container justify-content-center">
            <a class="navbar-brand justify-content-center">Status do Processo</a>
        </div>
    </nav>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_status_processo">Status Processo</label>
            {% render_field form.status_acompanhamento class+="form-control"%}
        </div>
        <div class="form-group col-md-6">
            <label for="inputnumero_processo">Número do Processo</label>
            <input type="number" name="numero_processo" class="form-control" required id="id_numero_processo" value="{{cadastro_list.numero_processo}}" disabled>
        </div>
    </div>
    <div class="form-group">
        <label for="notas">Observação</label>
        {% render_field form.notas class+="form-control" rows="4"%}
    </div>
    <a href={% url 'ListaProcesso' %} class="btn btn-danger btn-sm">Cancelar</a>
    <button type="submit" class="btn btn-success btn-sm">Finalizar Cadastro</button>
    
</form>
<form>
    <nav class="navbar navbar-light color-nav static-top">
        <div class="container justify-content-center">
            <a class="navbar-brand justify-content-center">Dados do Processo</a>
        </div>
    </nav>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputautor">Autor do Processo</label>
            <select name="fk_autor" class="form-control" required id="id_fk_autor" disabled>
                <option value="{{cadastro_list.fk_autor}}" selected>{{cadastro_list.fk_autor}}</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="inputnumero_processo">Número do Processo</label>
            <input type="number" name="numero_processo" class="form-control" required id="id_numero_processo" value="{{cadastro_list.numero_processo}}" disabled>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-7">
            <label for="inputnomereu">Nome do Réu</label>
            <input type="text" name="reu" maxlength="200" class="form-control" required id="id_reu" value="{{cadastro_list.reu}}" disabled>
        </div>
        <div class="form-group col-md-5">
            <label for="inputdocumento">Cpf/Cnpj</label>
            <input type="text" name="documento" maxlength="14" class="form-control" required id="id_documento" value="{{cadastro_list.documento}}" disabled>
        </div>
    </div>
    <div class="form-row">
        <label class="">Possui advogado ?</label>
        <div class="form-group col-md-4">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" name="advogado" value="0" class="custom-control-input" value="1" id="possuiadv1" {% if cadastro_list.advogado   ==  "1" %} checked="checked" {% endif %} disabled>
                <label class="custom-control-label" for="possuiadv1">Sim</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" name="advogado" value="0" class="custom-control-input" {% if cadastro_list.advogado !=  "1" %} checked="checked" {% endif %} value="0" id="possuiadv2" disabled>
                <label class="custom-control-label" for="possuiadv2">Não</label>
            </div>
        </div>
        <label class="">É segredo ?</label>
        <div class="form-group col-md-4">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" name="segredo" value="0" class="custom-control-input" {% if cadastro_list.segredo   ==  "1" %} checked="checked" {% endif %} value="1" id="segredo1" disabled>
                <label class="custom-control-label" for="segredo1">Sim</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" name="segredo" value="0" class="custom-control-input" {% if cadastro_list.segredo !=    "1" %} checked="checked" {% endif %} value="0" id="segredo2" disabled>
                <label class="custom-control-label" for="segredo2" checked>Não</label>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-light color-nav static-top">
        <div class="container justify-content-center">
            <a class="navbar-brand justify-content-center">Dados da Inicial</a>
        </div>
    </nav>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputrua">Rua</label>
            <input type="text" name="rua" maxlength="200" class="form-control" id="id_rua" value="{{cadastro_list.rua}}" disabled>
        </div>
        <div class="form-group col-md-1">
            <label for="inputnumero">Número</label>
            <input type="number" name="numero" class="form-control" id="id_numero" value="{{cadastro_list.numero}}" disabled>
        </div>
        <div class="form-group col-md-5">
            <label for="inputcomplemento">Complemento</label>
            <input type="text" name="complemento" class="form-control" id="inputcomplemento" value="  {% if cadastro_list.complemento is None %}
                                                                                                      {% else %}
                                                                                                      {{cadastro_list.complemento}}
                                                                                                      {% endif %}" disabled>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-5">
            <label for="inputbairro">Bairro</label>
            <input type="text" name="bairro" maxlength="200" class="form-control" id="id_bairro" value="{{cadastro_list.bairro}}" disabled>
        </div>
        <div class="form-group col-md-4">
            <label for="inputcidade">Cidade</label>
            <input type="text" name="cidade" maxlength="200" class="form-control" id="id_cidade" value="{{cadastro_list.cidade}}" disabled>
        </div>
        <div class="form-group col-md-3">
            <label for="inputcep">CEP</label>
            <input type="text" name="cep" maxlength="8" class="form-control" id="id_cep" value="{{cadastro_list.cep}}" disabled>
        </div>

    </div>
</form>




    {% endblock %}

Gerenciador/templates/Gerenciador/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Alexandre Victor">
    <title>Gerenciador de Processos</title>
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'Gerenciador/css/style.css' %}">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'Gerenciador/vendor/bootstrap/css/bootstrap.min.css' %}">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="{% static 'Gerenciador/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'Gerenciador/vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'Gerenciador/vendor/simple-line-icons/css/simple-line-icons.csss' %}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'Gerenciador/css/landing-page.css' %}">
</head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Gerenciador</a>
        <a class="btn btn-primary" href="#">Iniciar Sessão</a>
      </div>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    <!-- Footer -->
    <footer class="footer bg-light">
      <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                <!--<p class="text-muted small mb-4 mb-lg-0">&copy; Gerenciador 2018. All Rights Reserved.</p>-->
            </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'Gerenciador/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'Gerenciador/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>